Minh added: Header.tsx file and add some code in layout.tsx file
KingSand08/LikeHome pull request #51
Opened 2024-09-28 11:48 UTC by MinhHoaNguyen

Minh added: Header.tsx file and added some code in layout.tsx file

2024-09-29 07:40 UTC, ray-sjsu commented
Fixed build errors. Moved components `header` and `footer` into separate folder.

2024-09-29 07:51 UTC, ray-sjsu commented
Needs footer. Then, it should be good to close both issues.

2024-09-30 16:47 UTC, Luceium requested changes
Hey, good work. This is the first significantly large PR!
I reviewed it thoroughly and added a few comments.

Some more general feedback for the entire PR are as follows:
- Some of the indentation is off. Use a formater like Prettier to fix this.
- While testing this PR I noticed that it doesn't support darkmode. This isn't a p0 and shouldn't block this PR but let's make sure that we have an issue that will track this.

2024-09-30 16:47 UTC, Luceium commented on components/layout/Header.tsx
> +                        <div className="text-gray-700 hover:text-purple-600 cursor-pointer mr-8">Contact</div>
```suggestion
                        <div className="text-gray-700 hover:text-purple-600 cursor-pointer">Contact</div>
``` 
If you want a greater distance between the links and the sign in increase the gap on the parent flex container on line 19.

2024-10-03 21:01 UTC, Luceium commented
@MinhHoaNguyen & @ray-sjsu please make sure to respond to or resolve all comments before requesting another review.

2024-10-03 21:21 UTC, MinhHoaNguyen commented on app/layout.tsx
> +  weight: ['400'],
I changed. Don't need that code anymore.

2024-10-03 21:21 UTC, MinhHoaNguyen commented on components/layout/Footer.tsx
> +        <div className="container mx-auto">footer</div>
I tried with w-full but it doesn't look nice.

2024-10-03 21:21 UTC, MinhHoaNguyen commented on components/layout/Header.tsx
> +                <div className="flex items-center gap-2 xl:order-2">
code was changed. Don't use that code anymore.

2024-10-03 21:50 UTC, MinhHoaNguyen commented
close #13, #23, #33

2024-10-07 00:18 UTC, Luceium commented
The description of the PR needs to say closes #13, closes #23, and closes #33

2024-10-09 21:53 UTC, Luceium approved these changes

2024-10-11 22:09 UTC, KingSand08 approved these changes
Great job Raymund!

2024-10-11 22:09 UTC, merged