Booking Prisma and Server Actions
KingSand08/LikeHome pull request #70
Opened 2024-10-30 19:43 UTC by Luceium

2024-10-30 20:08 UTC, Luceium commented
```typescript
const dummySearchResults = [...] // populate this with tmp data that should have the same schema as the expected api results (see api docs for this)

// Example usage
const availbleRooms = dummySearchResults.filter(room => roomAvailbleDuringDates(room.id, startDate, endDate))

// Your task:
// This function should be a server action (see Next.js docs)
export function async roomAvailbleDuringDates(id: number, startDate: Date, endDate: Date) {
    ...
    // use prisma methods
    // if there are any bookings in our DB for that room during our requested dates then return false
    // it may be more optimal to only search through bookings for a specific hotel
}
// Note this function can be a lot more optimal if it returns all valid rooms instead of true or false
// the example expecting true or false is just to illustrate the behaviour and necessity.
```

2024-11-18 04:53 UTC, ray-sjsu requested changes

2024-11-18 04:53 UTC, ray-sjsu commented on roomAvailability.js
Delete this file, we don't need this anymore since `.ts` version of this already exists.

2024-11-18 04:53 UTC, ray-sjsu commented on roomAvailability.ts
https://nextjs.org/docs/app/building-your-application/routing/route-handlers

You would have to rename this to `route.ts`. And put in this directory: `app/api/availability`. See the link above to see how api's work in nextjs.

Also, change the `prisma.schema` to this structure. You can find this in `/lib/rapid-hotel-api/api-setup.ts` and import it into this `.ts`. This is what we will use. Update this `.ts` file accordingly to match the schema. Please make sure to fix any typescript errors before any commits.
![image](https://github.com/user-attachments/assets/1695f78b-5b92-4167-a2a3-d02f9f694a53)

2024-11-22 01:38 UTC, alia49 commented on roomAvailability.ts
I wasn't able to find the api-setup.ts. But is the rest of the script good? it should work if I can find the id's

2024-11-26 06:15 UTC, ray-sjsu commented
Currently, this branch is outdated from `main`. Also, rework of reservation system in progress.

https://github.com/KingSand08/LikeHome/pull/98 - new reservation system implementation (basic).

2024-11-26 06:15 UTC, closed without merging