#45 UI/UX About us and Contact Page/about
KingSand08/LikeHome pull request #86
Opened 2024-11-19 21:17 UTC by MinhHoaNguyen

The Contact Us form was added to the About page

2024-11-20 22:32 UTC, Luceium requested changes

2024-11-20 22:32 UTC, Luceium commented on app/about/page.tsx
> -      {/* Team Introduction */}
This seems like a good idea to keep. I'm not sure why we removed it.

2024-11-20 22:32 UTC, Luceium commented on app/about/page.tsx
> +      <div className="flex flex-col lg:flex-row gap-8">
```suggestion
      <div className="flex flex-col gap-8">
```
Contact us is typically at the bottom. Also this layout has a lot of dead space.

2024-11-20 22:32 UTC, Luceium commented on app/about/page.tsx
> +          <h2 className="text-3xl font-bold mb-4 text-center">Contact Us!</h2>
Components help readability. Contact us could and should be in a component.

2024-11-20 22:32 UTC, Luceium commented on app/about/page.tsx
> +                  <a href={`mailto:${member.email}`} className="hover:text-blue-500">
I think I linkedin link would be make more sense. I wouldn't want to give out my email.

2024-11-21 00:26 UTC, Luceium approved these changes
lgtm

2024-11-21 00:26 UTC, luSteven01 approved these changes
looks good to me

2024-11-21 00:28 UTC, merged